import { z } from "../_shared/schemas.ts";
import type { ExtracaoBase } from "./criacao.ts";
import { EXTRAIR_ADITIVO_PROMPT, EXTRAIR_CARTAO_PROMPT, EXTRAIR_CATEGORIA_PROMPT, EXTRAIR_CENTRO_CUSTO_PROMPT, EXTRAIR_CLIENTE_PROMPT, EXTRAIR_CONTA_PROMPT, EXTRAIR_DESPESA_PROMPT, EXTRAIR_DISCIPLINA_PROMPT, EXTRAIR_FOLHA_PROMPT, EXTRAIR_FORNECEDOR_PROMPT, EXTRAIR_LEAD_PROMPT, EXTRAIR_MARCO_PROMPT, EXTRAIR_PESSOA_PROMPT, EXTRAIR_PROJETO_PROMPT, EXTRAIR_PROPOSTA_PROMPT, EXTRAIR_RECEITA_PROMPT } from "./prompts.ts";
import { AGENTE_LABEL, AditivoExtractionSchema, Agente, CartaoExtractionSchema, CategoriaExtractionSchema, CentroCustoExtractionSchema, ClienteExtractionSchema, ContaExtractionSchema, DespesaExtractionSchema, DisciplinaExtractionSchema, FolhaExtractionSchema, FornecedorExtractionSchema, LeadExtractionSchema, MarcoExtractionSchema, PessoaExtractionSchema, ProjetoExtractionSchema, PropostaExtractionSchema, ReceitaExtractionSchema } from "./schemas.ts";

// Config estática por entidade criável. Runtime (db/admin/req/...) é injetado no dispatch.
export type EntidadeCfg = {
  agente: string;
  label: string;
  entidade: string;
  agentType: string;
  entityKey: string;
  prompt: string;
  schema: z.ZodType<ExtracaoBase>;
  requiredKeys: string[];
  instrucao: string;
  perguntaFallback: string;
  revisarMsg: string;
};

export const ENTIDADE_CFG: Record<string, EntidadeCfg> = {
  lead: {
    agente: "comercial",
    label: AGENTE_LABEL.comercial,
    entidade: "lead",
    agentType: "criar_lead",
    entityKey: "lead",
    prompt: EXTRAIR_LEAD_PROMPT,
    schema: LeadExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os campos do lead combinando TODAS as mensagens do usuário na conversa.",
    perguntaFallback: "Qual o nome do contato do lead?",
    revisarMsg: "Revise os dados do lead e confirme para criar.",
  },
  projeto: {
    agente: "projetos",
    label: AGENTE_LABEL.projetos,
    entidade: "projeto",
    agentType: "criar_projeto",
    entityKey: "projeto",
    prompt: EXTRAIR_PROJETO_PROMPT,
    schema: ProjetoExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os campos do projeto combinando TODAS as mensagens do usuário na conversa.",
    perguntaFallback: "Qual o nome do projeto?",
    revisarMsg: "Revise os dados do projeto e confirme para criar.",
  },
  receita: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "receita",
    agentType: "criar_receita",
    entityKey: "receita",
    prompt: EXTRAIR_RECEITA_PROMPT,
    schema: ReceitaExtractionSchema,
    requiredKeys: ["descricao", "valor"],
    instrucao: "Extraia os campos da receita combinando TODAS as mensagens do usuário na conversa.",
    perguntaFallback: "Qual a descrição e o valor da receita?",
    revisarMsg: "Revise a receita e confirme para lançar.",
  },
  despesa: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "despesa",
    agentType: "criar_despesa",
    entityKey: "despesa",
    prompt: EXTRAIR_DESPESA_PROMPT,
    schema: DespesaExtractionSchema,
    requiredKeys: ["descricao", "valor"],
    instrucao: "Extraia os campos da despesa combinando TODAS as mensagens do usuário na conversa.",
    perguntaFallback: "Qual a descrição e o valor da despesa?",
    revisarMsg: "Revise a despesa e confirme para lançar.",
  },
  cartao: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "cartao",
    agentType: "criar_cartao",
    entityKey: "cartao",
    prompt: EXTRAIR_CARTAO_PROMPT,
    schema: CartaoExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os dados do cartão da conversa.",
    perguntaFallback: "Qual o nome (apelido) do cartão?",
    revisarMsg: "Revise os dados do cartão e confirme para cadastrar.",
  },
  folha: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "folha",
    agentType: "fechar_folha",
    entityKey: "folha",
    prompt: EXTRAIR_FOLHA_PROMPT,
    schema: FolhaExtractionSchema,
    requiredKeys: ["mes", "ano"],
    instrucao: "Identifique o mês e o ano da folha a partir da conversa e da data de hoje.",
    perguntaFallback: "De qual mês e ano é a folha?",
    revisarMsg: "Revise o preview da folha e confirme para fechar.",
  },
  cliente: {
    agente: "comercial",
    label: AGENTE_LABEL.comercial,
    entidade: "cliente",
    agentType: "criar_cliente",
    entityKey: "cliente",
    prompt: EXTRAIR_CLIENTE_PROMPT,
    schema: ClienteExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os dados do cliente da conversa.",
    perguntaFallback: "Qual o nome do cliente?",
    revisarMsg: "Revise os dados do cliente e confirme para criar.",
  },
  fornecedor: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "fornecedor",
    agentType: "criar_fornecedor",
    entityKey: "fornecedor",
    prompt: EXTRAIR_FORNECEDOR_PROMPT,
    schema: FornecedorExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os dados do fornecedor.",
    perguntaFallback: "Qual o nome do fornecedor?",
    revisarMsg: "Revise os dados do fornecedor e confirme para criar.",
  },
  categoria: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "categoria",
    agentType: "criar_categoria",
    entityKey: "categoria",
    prompt: EXTRAIR_CATEGORIA_PROMPT,
    schema: CategoriaExtractionSchema,
    requiredKeys: ["nome", "tipo"],
    instrucao: "Extraia o nome e o tipo (Receita/Despesa) da categoria.",
    perguntaFallback: "Qual o nome e o tipo (receita ou despesa) da categoria?",
    revisarMsg: "Revise a categoria e confirme para criar.",
  },
  conta: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "conta",
    agentType: "criar_conta",
    entityKey: "conta",
    prompt: EXTRAIR_CONTA_PROMPT,
    schema: ContaExtractionSchema,
    requiredKeys: ["nome", "banco"],
    instrucao: "Extraia os dados da conta bancária.",
    perguntaFallback: "Qual o nome e o banco da conta?",
    revisarMsg: "Revise a conta e confirme para cadastrar.",
  },
  centro_custo: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "centro_custo",
    agentType: "criar_centro_custo",
    entityKey: "centro_custo",
    prompt: EXTRAIR_CENTRO_CUSTO_PROMPT,
    schema: CentroCustoExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia os dados do centro de custo.",
    perguntaFallback: "Qual o nome do centro de custo?",
    revisarMsg: "Revise o centro de custo e confirme para criar.",
  },
  pessoa: {
    agente: "projetos",
    label: "Agente de Pessoas",
    entidade: "pessoa",
    agentType: "criar_pessoa",
    entityKey: "pessoa",
    prompt: EXTRAIR_PESSOA_PROMPT,
    schema: PessoaExtractionSchema,
    requiredKeys: ["primeiro_nome", "sobrenome", "email"],
    instrucao: "Extraia os dados da pessoa.",
    perguntaFallback: "Qual o nome, sobrenome e e-mail da pessoa?",
    revisarMsg: "Revise os dados da pessoa e confirme para cadastrar.",
  },
  proposta: {
    agente: "comercial",
    label: AGENTE_LABEL.comercial,
    entidade: "proposta",
    agentType: "criar_proposta",
    entityKey: "proposta",
    prompt: EXTRAIR_PROPOSTA_PROMPT,
    schema: PropostaExtractionSchema,
    requiredKeys: ["titulo"],
    instrucao: "Extraia os dados da proposta.",
    perguntaFallback: "Qual o título da proposta?",
    revisarMsg: "Revise a proposta e confirme para criar.",
  },
  marco: {
    agente: "financeiro",
    label: AGENTE_LABEL.financeiro,
    entidade: "marco",
    agentType: "criar_marco",
    entityKey: "marco",
    prompt: EXTRAIR_MARCO_PROMPT,
    schema: MarcoExtractionSchema,
    requiredKeys: ["nome", "valor"],
    instrucao: "Extraia os dados do marco de faturamento.",
    perguntaFallback: "Qual o nome e o valor do marco?",
    revisarMsg: "Revise o marco e confirme para criar.",
  },
  disciplina: {
    agente: "projetos",
    label: AGENTE_LABEL.projetos,
    entidade: "disciplina",
    agentType: "criar_disciplina",
    entityKey: "disciplina",
    prompt: EXTRAIR_DISCIPLINA_PROMPT,
    schema: DisciplinaExtractionSchema,
    requiredKeys: ["nome"],
    instrucao: "Extraia a disciplina e o projeto-alvo da conversa.",
    perguntaFallback: "Qual disciplina e em qual projeto?",
    revisarMsg: "Revise a disciplina e confirme para adicionar.",
  },
  aditivo: {
    agente: "projetos",
    label: AGENTE_LABEL.projetos,
    entidade: "aditivo",
    agentType: "criar_aditivo",
    entityKey: "aditivo",
    prompt: EXTRAIR_ADITIVO_PROMPT,
    schema: AditivoExtractionSchema,
    requiredKeys: ["descricao"],
    instrucao: "Extraia o aditivo (descrição, justificativa, itens) e o projeto-alvo.",
    perguntaFallback: "Qual o resumo do aditivo e em qual projeto?",
    revisarMsg: "Revise o aditivo e confirme para criar (como rascunho).",
  },
};
