ALTER TABLE propostas
  ADD COLUMN IF NOT EXISTS contrato_enviado   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS contrato_assinado  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS contrato_recusado  BOOLEAN NOT NULL DEFAULT FALSE;
